model:
  arch: minigpt_v2
  model_type: pretrain
  max_txt_len: 2048
  end_sym: "</s>"
  low_resource: False
  cfg-path: "/content/drive/MyDrive/chart2text/MiniGPT-4/eval_configs/minighptv2_more_eval_chart2text_warmup.yaml"
  prompt_template: '[INST] {} [/INST]'
  llama_model: "meta-llama/Llama-2-7b-chat-hf"
  ckpt: "/content/drive/MyDrive/chart2text/MiniGPT-4/output_more/save_checkpoint/20240402153/checkpoint_1.pth"
  lora_r: 64
  lora_alpha: 16
  lora_target_modules: 
    - "q_proj"
    - "v_proj"
    - "k_proj"
    - "o_proj"
    - "gate_proj"
    - "down_proj"
    - "up_proj"

datasets:
  chart2text_warmup:
    vis_processor:
      train:
        name: "blip2_image_train"
        image_size: 448
    text_processor:
      train:
        name: "blip_caption"


evaluation_datasets:
  refcoco:
    eval_file_path: /path/to/eval/annotation/path  
    img_path: /path/to/eval/image/path      
    max_new_tokens: 20
    batch_size: 10
  refcocog:
    eval_file_path: /path/to/eval/annotation/path  
    img_path: /path/to/eval/image/path    
    max_new_tokens: 20
    batch_size: 10
  refcoco+:
    eval_file_path: /path/to/eval/annotation/path  
    img_path: /path/to/eval/image/path    
    max_new_tokens: 20
    batch_size: 10
  gqa:
    eval_file_path: /path/to/eval/annotation/path  
    img_path: /path/to/eval/image/path    
    max_new_tokens: 20
    batch_size: 10
  okvqa:
    eval_file_path: /path/to/eval/annotation/path  
    img_path: /path/to/eval/image/path     
    max_new_tokens: 20
    batch_size: 10
  vizwiz:
    eval_file_path: /path/to/eval/annotation/path  
    img_path: /path/to/eval/image/path    
    max_new_tokens: 20
    batch_size: 10
  iconvqa:
    eval_file_path: /path/to/eval/annotation/path  
    img_path: /path/to/eval/image/path    
    max_new_tokens: 20
    batch_size: 10
  vsr:
    eval_file_path: cambridgeltl/vsr_zeroshot 
    img_path: /path/to/eval/image/path    
    max_new_tokens: 20
    batch_size: 10
  hm:
    eval_file_path: /path/to/eval/annotation/path  
    img_path: /path/to/eval/image/path 
    max_new_tokens: 20
    batch_size: 100

  chart2text_warmup:
    vis_processor:
      train:
        name: "blip2_image_train"
        image_size: 448
    text_processor:
      train:
        name: "blip_caption"
        
    root_path: /content/drive/MyDrive/chart2text/dataset
    max_new_tokens: 2048
    batch_size: 1

run:
  task: image_text_pretrain
  name: minigptv2_evaluation
  save_path: /content/drive/MyDrive/chart2text/MiniGPT-4/eval_result