model:
  arch: minigpt_v2
  model_type: pretrain
  max_txt_len: 4096
  image_size: 448
  end_sym: "</s>"
  llama_model: "meta-llama/Llama-2-7b-chat-hf"
  ckpt: "/content/drive/MyDrive/chart2text/MiniGPT-4/output_more/save_checkpoint/20240501102/checkpoint_9.pth"
  use_grad_checkpoint: True
  chat_template: True
  lora_r: 64
  lora_alpha: 16
  lora_target_modules: 
    - "q_proj"
    - "v_proj"
    - "k_proj"
    - "o_proj"
    - "gate_proj"
    - "down_proj"
    - "up_proj"

datasets:
  chart2text_warmup:
    batch_size: 2
    vis_processor:
      train:
        name: "blip2_image_train"
        image_size: 448
    text_processor:
      train:
        name: "blip_caption"
    sample_ratio: 50

run:
  task: image_text_pretrain
  # optimizer
  lr_sched: "linear_warmup_cosine_lr"
  init_lr: 1e-5
  min_lr: 1e-7
  warmup_lr: 1e-6

  weight_decay: 0.001
  max_epoch: 10
  num_workers: 1
  warmup_steps: 100
  iters_per_epoch: 13000

  seed: 42
  output_dir: "/content/drive/MyDrive/chart2text/MiniGPT-4/output_more/save_checkpoint"

  amp: True
  resume_ckpt_path: null

  evaluate: False 
  train_splits: ["train"]

  device: "cuda"
  world_size: 1
  dist_url: "env://"
  distributed: True

  wandb_log: True
  job_name: minigptv2_more_finetune
